# Generated by Django 6.1.1 on 2026-09-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tostador', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cafes/')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anónimo', max_length=50)),
                ('molienda', models.CharField(max_length=50)),
                ('temperatura', models.IntegerField()),
                ('ratio', models.CharField(max_length=20)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='cafes.cafe')),
            ],
        ),
    ]
