# Generated by Django 6.1.1 on 2026-09-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='agua_total',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='receta',
            name='bloom_agua',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='receta',
            name='bloom_segundos',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='receta',
            name='clicks_molino',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='receta',
            name='gramos_cafe',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=4),
        ),
        migrations.AddField(
            model_name='receta',
            name='molino',
            field=models.CharField(default='Comandante C40', max_length=50),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_total',
            field=models.CharField(default='3:00', max_length=10),
        ),
        migrations.AddField(
            model_name='receta',
            name='vertidos',
            field=models.CharField(default='', max_length=200),
        ),
    ]
