# Generated by Django 6.1.1 on 2026-09-21 04:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_receta_agua_total_receta_bloom_agua_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['tostador', 'nombre'], 'verbose_name': 'café', 'verbose_name_plural': 'cafés'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['cafe', 'autor'], 'verbose_name': 'receta', 'verbose_name_plural': 'recetas'},
        ),
        migrations.AlterField(
            model_name='cafe',
            name='imagen',
            field=models.ImageField(blank=True, default='', help_text='Fotografía del envase. Se procesa y valida con Pillow.', upload_to='cafes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafe',
            name='nombre',
            field=models.CharField(help_text='Nombre del lote, finca o variedad. Ej: Bourbon Chiroso Finca La Betania.', max_length=100),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='origen',
            field=models.CharField(help_text='Zona y país de origen del grano.', max_length=100),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='tostador',
            field=models.CharField(help_text='Tostaduría responsable del tueste.', max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='agua_total',
            field=models.PositiveSmallIntegerField(default=250, help_text='Agua total vertida en mililitros.', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='autor',
            field=models.CharField(default='Anónimo', help_text='Barista que firma la receta.', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='bloom_agua',
            field=models.PositiveSmallIntegerField(default=45, help_text='Agua del bloom en gramos (2 a 3 veces la dosis).'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='bloom_segundos',
            field=models.PositiveSmallIntegerField(default=40, help_text='Duración de la pre-infusión en segundos.', validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cafe',
            field=models.ForeignKey(help_text='Café sobre el que se aplica esta receta.', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='cafes.cafe'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='clicks_molino',
            field=models.PositiveSmallIntegerField(default=26, help_text='Clicks desde cero del molino indicado.', validators=[django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='gramos_cafe',
            field=models.DecimalField(decimal_places=1, default=Decimal('15.0'), help_text='Dosis de café molido en gramos.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('5.0')), django.core.validators.MaxValueValidator(Decimal('60.0'))]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='molienda',
            field=models.CharField(help_text='Descripción táctil de la molienda. Ej: media (sal gruesa).', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='molino',
            field=models.CharField(default='Comandante C40', help_text='Marca y modelo del molino usado como referencia.', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ratio',
            field=models.CharField(help_text='Proporción café:agua declarada por el barista. Ej: 1:16.', max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='temperatura',
            field=models.PositiveSmallIntegerField(help_text='Temperatura del agua en grados Celsius (85-96).', validators=[django.core.validators.MinValueValidator(85), django.core.validators.MaxValueValidator(96)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_total',
            field=models.CharField(default='3:00', help_text='Tiempo objetivo de extracción en formato mm:ss.', max_length=10),
        ),
        migrations.AlterField(
            model_name='receta',
            name='vertidos',
            field=models.CharField(blank=True, help_text='Etapas del vertido. Ej: 0:00 45g, 0:40 140g, 1:20 240g.', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='cafe',
            constraint=models.UniqueConstraint(fields=('nombre', 'tostador'), name='lote_unico_por_tostador'),
        ),
    ]
