# Generated by Django 6.1.1 on 2026-09-28 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafe_options_alter_receta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['cafe', 'autor'], 'permissions': [('publicar_receta', 'Puede publicar recetas en el catálogo')], 'verbose_name': 'receta', 'verbose_name_plural': 'recetas'},
        ),
        migrations.AddField(
            model_name='receta',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario autenticado que cargó la receta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receta',
            name='publicada',
            field=models.BooleanField(default=True, help_text='Si está desmarcada, la receta no aparece en el catálogo público.'),
        ),
    ]
