# Generated by Django 6.1.1 on 2026-09-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_grupo_baristas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
