"""
Django settings for catalogo_cafe project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECRET_KEY y DEBUG salen del .env (python-decouple). El archivo .env no se
# sube a GitHub; en el repo público solo queda la plantilla .env.example.
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=True, cast=bool)

# Conecta los dominios permitidos (DNS) leyendo la configuración del entorno de despliegue (Hosting)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1, localhost', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        'cafes.apps.CafesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'catalogo_cafe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catalogo_cafe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Motor y credenciales salen del .env: en local SQLite (cero instalación) y
# en un PaaS se apunta a PostgreSQL sin tocar este archivo. ATOMIC_REQUESTS
# envuelve cada petición en una transacción: si la vista falla, no queda
# un receta a medias. Las sesiones de django.contrib.sessions también se
# persisten en esta misma base (tabla django_session).

_db_engine = config('DB_ENGINE', default='django.db.backends.sqlite3')
_db_name = config('DB_NAME', default='')
if not _db_name:
    _db_name = str(BASE_DIR / 'db.sqlite3')
elif _db_engine.endswith('sqlite3') and not Path(_db_name).is_absolute():
    _db_name = str(BASE_DIR / _db_name)

DATABASES = {
    'default': {
        'ENGINE': _db_engine,
        'NAME': _db_name,
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
        'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=0, cast=int),
    }
}

# Datos de prueba
# https://docs.djangoproject.com/en/6.1/howto/initial-data/

# Los fixtures viven en una carpeta propia del proyecto, así que se declara
# para poder cargarlos con: python manage.py loaddata datos.json
FIXTURE_DIRS = [BASE_DIR / 'fixtures']


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (imágenes de los cafés)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Autenticación y sesiones
# https://docs.djangoproject.com/en/6.1/topics/auth/default/
# https://docs.djangoproject.com/en/6.1/topics/http/sessions/

LOGIN_URL = 'cafes:login'
LOGIN_REDIRECT_URL = 'cafes:mis_recetas'
LOGOUT_REDIRECT_URL = 'cafes:catalogo'

# La sesión vive 1 hora de inactividad y se destruye al cerrar el navegador.
# HttpOnly impide que JavaScript lea la cookie; SameSite=Lax mitiga CSRF.
SESSION_COOKIE_AGE = 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
